application: inecep-2017
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|php))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|php))

- url: .*
  script: main.py
